In [2]:
import torch
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
df = pd.read_csv("bonus_dataset.csv")
df.head()

  employee_id  performance  years_of_experience  projects_completed  bonus
0     EMP_001            7                    2                   4    124
1     EMP_002            4                    1                   4     82
2     EMP_003            8                    7                  10    178
3     EMP_004            5                    7                   8    138
4     EMP_005            7                    8                   9    170

In [7]:
performance = torch.tensor(df['performance'].values, dtype=torch.float32)
years_of_experience = torch.tensor(df['years_of_experience'].values, dtype=torch.float32)
projects_completed = torch.tensor(df['projects_completed'].values, dtype=torch.float32)
bonus = torch.tensor(df['bonus'].values, dtype=torch.float32)

### Batch Gradient Descent

In [22]:
w1 = torch.rand(1, requires_grad=True)
w2 = torch.rand(1, requires_grad=True)
w3 = torch.rand(1, requires_grad=True)
bias = torch.rand(1, requires_grad=True)

# print(w1, w2, w3, bias)
learning_rate = 0.001
epochs = 50000

for epoch in range(epochs):
    predicted_bonus = w1 * performance + w2 * years_of_experience + w3 * projects_completed + bias

    loss = ((predicted_bonus - bonus)**2).mean()

    loss.backward()

    with torch.no_grad():
        w1 -= learning_rate * w1.grad
        w2 -= learning_rate * w2.grad
        w3 -= learning_rate * w3.grad
        bias -= learning_rate * bias.grad

    # Zero the gradients after updating
    w1.grad.zero_()
    w2.grad.zero_()
    w3.grad.zero_()
    bias.grad.zero_()

    # Print the loss at regular intervals
    if (epoch + 1) % 100 == 0:
        print(f"Epoch [{epoch + 1}/{epochs}], Loss: {loss.item():.4f}")

Epoch [100/50000], Loss: 25.3291
Epoch [200/50000], Loss: 19.3553
Epoch [300/50000], Loss: 18.8824
Epoch [400/50000], Loss: 18.4587
Epoch [500/50000], Loss: 18.0447
Epoch [600/50000], Loss: 17.6401
Epoch [700/50000], Loss: 17.2445
Epoch [800/50000], Loss: 16.8578
Epoch [900/50000], Loss: 16.4798
Epoch [1000/50000], Loss: 16.1103
Epoch [1100/50000], Loss: 15.7490
Epoch [1200/50000], Loss: 15.3959
Epoch [1300/50000], Loss: 15.0506
Epoch [1400/50000], Loss: 14.7131
Epoch [1500/50000], Loss: 14.3832
Epoch [1600/50000], Loss: 14.0607
Epoch [1700/50000], Loss: 13.7454
Epoch [1800/50000], Loss: 13.4372
Epoch [1900/50000], Loss: 13.1359
Epoch [2000/50000], Loss: 12.8413
Epoch [2100/50000], Loss: 12.5533
Epoch [2200/50000], Loss: 12.2719
Epoch [2300/50000], Loss: 11.9967
Epoch [2400/50000], Loss: 11.7277
Epoch [2500/50000], Loss: 11.4647
Epoch [2600/50000], Loss: 11.2076
Epoch [2700/50000], Loss: 10.9563
Epoch [2800/50000], Loss: 10.7106
Epoch [2900/50000], Loss: 10.4704
Epoch [3000/50000], Loss: 10.2357
Epoch [3100/50000], Loss: 10.0061
Epoch [3200/50000], Loss: 9.7818
Epoch [3300/50000], Loss: 9.5624
Epoch [3400/50000], Loss: 9.3480
Epoch [3500/50000], Loss: 9.1384
Epoch [3600/50000], Loss: 8.9335
Epoch [3700/50000], Loss: 8.7331
Epoch [3800/50000], Loss: 8.5373
Epoch [3900/50000], Loss: 8.3459
Epoch [4000/50000], Loss: 8.1587
Epoch [4100/50000], Loss: 7.9758
Epoch [4200/50000], Loss: 7.7969
Epoch [4300/50000], Loss: 7.6221
Epoch [4400/50000], Loss: 7.4512
Epoch [4500/50000], Loss: 7.2841
Epoch [4600/50000], Loss: 7.1208
Epoch [4700/50000], Loss: 6.9611
Epoch [4800/50000], Loss: 6.8050
Epoch [4900/50000], Loss: 6.6524
Epoch [5000/50000], Loss: 6.5032
Epoch [5100/50000], Loss: 6.3574
Epoch [5200/50000], Loss: 6.2149
Epoch [5300/50000], Loss: 6.0755
Epoch [5400/50000], Loss: 5.9393
Epoch [5500/50000], Loss: 5.8061
Epoch [5600/50000], Loss: 5.6759
Epoch [5700/50000], Loss: 5.5486
Epoch [5800/50000], Loss: 5.4242
Epoch [5900/50000], Loss: 5.3026
Epoch [6000/50000], Loss: 5.1837
Epoch [6100/50000], Loss: 5.0674
Epoch [6200/50000], Loss: 4.9538
Epoch [6300/50000], Loss: 4.8427
Epoch [6400/50000], Loss: 4.7341
Epoch [6500/50000], Loss: 4.6280
Epoch [6600/50000], Loss: 4.5242
Epoch [6700/50000], Loss: 4.4228
Epoch [6800/50000], Loss: 4.3236
Epoch [6900/50000], Loss: 4.2266
Epoch [7000/50000], Loss: 4.1319
Epoch [7100/50000], Loss: 4.0392
Epoch [7200/50000], Loss: 3.9486
Epoch [7300/50000], Loss: 3.8601
Epoch [7400/50000], Loss: 3.7735
Epoch [7500/50000], Loss: 3.6889
Epoch [7600/50000], Loss: 3.6062
Epoch [7700/50000], Loss: 3.5253
Epoch [7800/50000], Loss: 3.4463
Epoch [7900/50000], Loss: 3.3690
Epoch [8000/50000], Loss: 3.2935
Epoch [8100/50000], Loss: 3.2196
Epoch [8200/50000], Loss: 3.1474
Epoch [8300/50000], Loss: 3.0768
Epoch [8400/50000], Loss: 3.0079
Epoch [8500/50000], Loss: 2.9404
Epoch [8600/50000], Loss: 2.8745
Epoch [8700/50000], Loss: 2.8100
Epoch [8800/50000], Loss: 2.7470
Epoch [8900/50000], Loss: 2.6854
Epoch [9000/50000], Loss: 2.6252
Epoch [9100/50000], Loss: 2.5663
Epoch [9200/50000], Loss: 2.5088
Epoch [9300/50000], Loss: 2.4525
Epoch [9400/50000], Loss: 2.3975
Epoch [9500/50000], Loss: 2.3438
Epoch [9600/50000], Loss: 2.2912
Epoch [9700/50000], Loss: 2.2398
Epoch [9800/50000], Loss: 2.1896
Epoch [9900/50000], Loss: 2.1405
Epoch [10000/50000], Loss: 2.0925
Epoch [10100/50000], Loss: 2.0456
Epoch [10200/50000], Loss: 1.9997
Epoch [10300/50000], Loss: 1.9549
Epoch [10400/50000], Loss: 1.9110
Epoch [10500/50000], Loss: 1.8682
Epoch [10600/50000], Loss: 1.8263
Epoch [10700/50000], Loss: 1.7854
Epoch [10800/50000], Loss: 1.7453
Epoch [10900/50000], Loss: 1.7062
Epoch [11000/50000], Loss: 1.6679
Epoch [11100/50000], Loss: 1.6305
Epoch [11200/50000], Loss: 1.5940
Epoch [11300/50000], Loss: 1.5582
Epoch [11400/50000], Loss: 1.5233
Epoch [11500/50000], Loss: 1.4891
Epoch [11600/50000], Loss: 1.4557
Epoch [11700/50000], Loss: 1.4231
Epoch [11800/50000], Loss: 1.3912
Epoch [11900/50000], Loss: 1.3600
Epoch [12000/50000], Loss: 1.3295
Epoch [12100/50000], Loss: 1.2997
Epoch [12200/50000], Loss: 1.2705
Epoch [12300/50000], Loss: 1.2420
Epoch [12400/50000], Loss: 1.2142
Epoch [12500/50000], Loss: 1.1870
Epoch [12600/50000], Loss: 1.1604
Epoch [12700/50000], Loss: 1.1343
Epoch [12800/50000], Loss: 1.1089
Epoch [12900/50000], Loss: 1.0840
Epoch [13000/50000], Loss: 1.0597
Epoch [13100/50000], Loss: 1.0360
Epoch [13200/50000], Loss: 1.0127
Epoch [13300/50000], Loss: 0.9900
Epoch [13400/50000], Loss: 0.9678
Epoch [13500/50000], Loss: 0.9461
Epoch [13600/50000], Loss: 0.9249
Epoch [13700/50000], Loss: 0.9042
Epoch [13800/50000], Loss: 0.8839
Epoch [13900/50000], Loss: 0.8641
Epoch [14000/50000], Loss: 0.8447
Epoch [14100/50000], Loss: 0.8258
Epoch [14200/50000], Loss: 0.8072
Epoch [14300/50000], Loss: 0.7891
Epoch [14400/50000], Loss: 0.7714
Epoch [14500/50000], Loss: 0.7541
Epoch [14600/50000], Loss: 0.7372
Epoch [14700/50000], Loss: 0.7207
Epoch [14800/50000], Loss: 0.7045
Epoch [14900/50000], Loss: 0.6887
Epoch [15000/50000], Loss: 0.6733
Epoch [15100/50000], Loss: 0.6582
Epoch [15200/50000], Loss: 0.6435
Epoch [15300/50000], Loss: 0.6290
Epoch [15400/50000], Loss: 0.6149
Epoch [15500/50000], Loss: 0.6011
Epoch [15600/50000], Loss: 0.5876
Epoch [15700/50000], Loss: 0.5745
Epoch [15800/50000], Loss: 0.5616
Epoch [15900/50000], Loss: 0.5490
Epoch [16000/50000], Loss: 0.5367
Epoch [16100/50000], Loss: 0.5247
Epoch [16200/50000], Loss: 0.5129
Epoch [16300/50000], Loss: 0.5014
Epoch [16400/50000], Loss: 0.4901
Epoch [16500/50000], Loss: 0.4792
Epoch [16600/50000], Loss: 0.4684
Epoch [16700/50000], Loss: 0.4579
Epoch [16800/50000], Loss: 0.4476
Epoch [16900/50000], Loss: 0.4376
Epoch [17000/50000], Loss: 0.4278
Epoch [17100/50000], Loss: 0.4182
Epoch [17200/50000], Loss: 0.4088
Epoch [17300/50000], Loss: 0.3997
Epoch [17400/50000], Loss: 0.3907
Epoch [17500/50000], Loss: 0.3819
Epoch [17600/50000], Loss: 0.3734
Epoch [17700/50000], Loss: 0.3650
Epoch [17800/50000], Loss: 0.3568
Epoch [17900/50000], Loss: 0.3488
Epoch [18000/50000], Loss: 0.3410
Epoch [18100/50000], Loss: 0.3333
Epoch [18200/50000], Loss: 0.3259
Epoch [18300/50000], Loss: 0.3186
Epoch [18400/50000], Loss: 0.3114
Epoch [18500/50000], Loss: 0.3044
Epoch [18600/50000], Loss: 0.2976
Epoch [18700/50000], Loss: 0.2909
Epoch [18800/50000], Loss: 0.2844
Epoch [18900/50000], Loss: 0.2780
Epoch [19000/50000], Loss: 0.2718
Epoch [19100/50000], Loss: 0.2657
Epoch [19200/50000], Loss: 0.2598
Epoch [19300/50000], Loss: 0.2539
Epoch [19400/50000], Loss: 0.2482
Epoch [19500/50000], Loss: 0.2427
Epoch [19600/50000], Loss: 0.2372
Epoch [19700/50000], Loss: 0.2319
Epoch [19800/50000], Loss: 0.2267
Epoch [19900/50000], Loss: 0.2216
Epoch [20000/50000], Loss: 0.2167
Epoch [20100/50000], Loss: 0.2118
Epoch [20200/50000], Loss: 0.2070
Epoch [20300/50000], Loss: 0.2024
Epoch [20400/50000], Loss: 0.1979
Epoch [20500/50000], Loss: 0.1934
Epoch [20600/50000], Loss: 0.1891
Epoch [20700/50000], Loss: 0.1849
Epoch [20800/50000], Loss: 0.1807
Epoch [20900/50000], Loss: 0.1767
Epoch [21000/50000], Loss: 0.1727
Epoch [21100/50000], Loss: 0.1688
Epoch [21200/50000], Loss: 0.1650
Epoch [21300/50000], Loss: 0.1613
Epoch [21400/50000], Loss: 0.1577
Epoch [21500/50000], Loss: 0.1542
Epoch [21600/50000], Loss: 0.1507
Epoch [21700/50000], Loss: 0.1473
Epoch [21800/50000], Loss: 0.1440
Epoch [21900/50000], Loss: 0.1408
Epoch [22000/50000], Loss: 0.1377
Epoch [22100/50000], Loss: 0.1346
Epoch [22200/50000], Loss: 0.1316
Epoch [22300/50000], Loss: 0.1286
Epoch [22400/50000], Loss: 0.1257
Epoch [22500/50000], Loss: 0.1229
Epoch [22600/50000], Loss: 0.1201
Epoch [22700/50000], Loss: 0.1175
Epoch [22800/50000], Loss: 0.1148
Epoch [22900/50000], Loss: 0.1122
Epoch [23000/50000], Loss: 0.1097
Epoch [23100/50000], Loss: 0.1073
Epoch [23200/50000], Loss: 0.1049
Epoch [23300/50000], Loss: 0.1025
Epoch [23400/50000], Loss: 0.1002
Epoch [23500/50000], Loss: 0.0980
Epoch [23600/50000], Loss: 0.0958
Epoch [23700/50000], Loss: 0.0936
Epoch [23800/50000], Loss: 0.0915
Epoch [23900/50000], Loss: 0.0895
Epoch [24000/50000], Loss: 0.0875
Epoch [24100/50000], Loss: 0.0855
Epoch [24200/50000], Loss: 0.0836
Epoch [24300/50000], Loss: 0.0817
Epoch [24400/50000], Loss: 0.0799
Epoch [24500/50000], Loss: 0.0781
Epoch [24600/50000], Loss: 0.0763
Epoch [24700/50000], Loss: 0.0746
Epoch [24800/50000], Loss: 0.0730
Epoch [24900/50000], Loss: 0.0713
Epoch [25000/50000], Loss: 0.0697
Epoch [25100/50000], Loss: 0.0682
Epoch [25200/50000], Loss: 0.0666
Epoch [25300/50000], Loss: 0.0651
Epoch [25400/50000], Loss: 0.0637
Epoch [25500/50000], Loss: 0.0622
Epoch [25600/50000], Loss: 0.0608
Epoch [25700/50000], Loss: 0.0595
Epoch [25800/50000], Loss: 0.0582
Epoch [25900/50000], Loss: 0.0568
Epoch [26000/50000], Loss: 0.0556
Epoch [26100/50000], Loss: 0.0543
Epoch [26200/50000], Loss: 0.0531
Epoch [26300/50000], Loss: 0.0519
Epoch [26400/50000], Loss: 0.0508
Epoch [26500/50000], Loss: 0.0496
Epoch [26600/50000], Loss: 0.0485
Epoch [26700/50000], Loss: 0.0474
Epoch [26800/50000], Loss: 0.0464
Epoch [26900/50000], Loss: 0.0453
Epoch [27000/50000], Loss: 0.0443
Epoch [27100/50000], Loss: 0.0433
Epoch [27200/50000], Loss: 0.0423
Epoch [27300/50000], Loss: 0.0414
Epoch [27400/50000], Loss: 0.0405
Epoch [27500/50000], Loss: 0.0396
Epoch [27600/50000], Loss: 0.0387
Epoch [27700/50000], Loss: 0.0378
Epoch [27800/50000], Loss: 0.0369
Epoch [27900/50000], Loss: 0.0361
Epoch [28000/50000], Loss: 0.0353
Epoch [28100/50000], Loss: 0.0345
Epoch [28200/50000], Loss: 0.0337
Epoch [28300/50000], Loss: 0.0330
Epoch [28400/50000], Loss: 0.0322
Epoch [28500/50000], Loss: 0.0315
Epoch [28600/50000], Loss: 0.0308
Epoch [28700/50000], Loss: 0.0301
Epoch [28800/50000], Loss: 0.0295
Epoch [28900/50000], Loss: 0.0288
Epoch [29000/50000], Loss: 0.0281
Epoch [29100/50000], Loss: 0.0275
Epoch [29200/50000], Loss: 0.0269
Epoch [29300/50000], Loss: 0.0263
Epoch [29400/50000], Loss: 0.0257
Epoch [29500/50000], Loss: 0.0251
Epoch [29600/50000], Loss: 0.0246
Epoch [29700/50000], Loss: 0.0240
Epoch [29800/50000], Loss: 0.0235
Epoch [29900/50000], Loss: 0.0230
Epoch [30000/50000], Loss: 0.0224
Epoch [30100/50000], Loss: 0.0219
Epoch [30200/50000], Loss: 0.0214
Epoch [30300/50000], Loss: 0.0210
Epoch [30400/50000], Loss: 0.0205
Epoch [30500/50000], Loss: 0.0200
Epoch [30600/50000], Loss: 0.0196
Epoch [30700/50000], Loss: 0.0191
Epoch [30800/50000], Loss: 0.0187
Epoch [30900/50000], Loss: 0.0183
Epoch [31000/50000], Loss: 0.0179
Epoch [31100/50000], Loss: 0.0175
Epoch [31200/50000], Loss: 0.0171
Epoch [31300/50000], Loss: 0.0167
Epoch [31400/50000], Loss: 0.0163
Epoch [31500/50000], Loss: 0.0160
Epoch [31600/50000], Loss: 0.0156
Epoch [31700/50000], Loss: 0.0153
Epoch [31800/50000], Loss: 0.0149
Epoch [31900/50000], Loss: 0.0146
Epoch [32000/50000], Loss: 0.0143
Epoch [32100/50000], Loss: 0.0139
Epoch [32200/50000], Loss: 0.0136
Epoch [32300/50000], Loss: 0.0133
Epoch [32400/50000], Loss: 0.0130
Epoch [32500/50000], Loss: 0.0127
Epoch [32600/50000], Loss: 0.0124
Epoch [32700/50000], Loss: 0.0122
Epoch [32800/50000], Loss: 0.0119
Epoch [32900/50000], Loss: 0.0116
Epoch [33000/50000], Loss: 0.0114
Epoch [33100/50000], Loss: 0.0111
Epoch [33200/50000], Loss: 0.0109
Epoch [33300/50000], Loss: 0.0106
Epoch [33400/50000], Loss: 0.0104
Epoch [33500/50000], Loss: 0.0101
Epoch [33600/50000], Loss: 0.0099
Epoch [33700/50000], Loss: 0.0097
Epoch [33800/50000], Loss: 0.0095
Epoch [33900/50000], Loss: 0.0093
Epoch [34000/50000], Loss: 0.0091
Epoch [34100/50000], Loss: 0.0089
Epoch [34200/50000], Loss: 0.0087
Epoch [34300/50000], Loss: 0.0085
Epoch [34400/50000], Loss: 0.0083
Epoch [34500/50000], Loss: 0.0081
Epoch [34600/50000], Loss: 0.0079
Epoch [34700/50000], Loss: 0.0077
Epoch [34800/50000], Loss: 0.0076
Epoch [34900/50000], Loss: 0.0074
Epoch [35000/50000], Loss: 0.0072
Epoch [35100/50000], Loss: 0.0071
Epoch [35200/50000], Loss: 0.0069
Epoch [35300/50000], Loss: 0.0067
Epoch [35400/50000], Loss: 0.0066
Epoch [35500/50000], Loss: 0.0064
Epoch [35600/50000], Loss: 0.0063
Epoch [35700/50000], Loss: 0.0062
Epoch [35800/50000], Loss: 0.0060
Epoch [35900/50000], Loss: 0.0059
Epoch [36000/50000], Loss: 0.0058
Epoch [36100/50000], Loss: 0.0056
Epoch [36200/50000], Loss: 0.0055
Epoch [36300/50000], Loss: 0.0054
Epoch [36400/50000], Loss: 0.0053
Epoch [36500/50000], Loss: 0.0051
Epoch [36600/50000], Loss: 0.0050
Epoch [36700/50000], Loss: 0.0049
Epoch [36800/50000], Loss: 0.0048
Epoch [36900/50000], Loss: 0.0047
Epoch [37000/50000], Loss: 0.0046
Epoch [37100/50000], Loss: 0.0045
Epoch [37200/50000], Loss: 0.0044
Epoch [37300/50000], Loss: 0.0043
Epoch [37400/50000], Loss: 0.0042
Epoch [37500/50000], Loss: 0.0041
Epoch [37600/50000], Loss: 0.0040
Epoch [37700/50000], Loss: 0.0039
Epoch [37800/50000], Loss: 0.0038
Epoch [37900/50000], Loss: 0.0037
Epoch [38000/50000], Loss: 0.0037
Epoch [38100/50000], Loss: 0.0036
Epoch [38200/50000], Loss: 0.0035
Epoch [38300/50000], Loss: 0.0034
Epoch [38400/50000], Loss: 0.0033
Epoch [38500/50000], Loss: 0.0033
Epoch [38600/50000], Loss: 0.0032
Epoch [38700/50000], Loss: 0.0031
Epoch [38800/50000], Loss: 0.0031
Epoch [38900/50000], Loss: 0.0030
Epoch [39000/50000], Loss: 0.0029
Epoch [39100/50000], Loss: 0.0029
Epoch [39200/50000], Loss: 0.0028
Epoch [39300/50000], Loss: 0.0027
Epoch [39400/50000], Loss: 0.0027
Epoch [39500/50000], Loss: 0.0026
Epoch [39600/50000], Loss: 0.0025
Epoch [39700/50000], Loss: 0.0025
Epoch [39800/50000], Loss: 0.0024
Epoch [39900/50000], Loss: 0.0024
Epoch [40000/50000], Loss: 0.0023
Epoch [40100/50000], Loss: 0.0023
Epoch [40200/50000], Loss: 0.0022
Epoch [40300/50000], Loss: 0.0022
Epoch [40400/50000], Loss: 0.0021
Epoch [40500/50000], Loss: 0.0021
Epoch [40600/50000], Loss: 0.0020
Epoch [40700/50000], Loss: 0.0020
Epoch [40800/50000], Loss: 0.0019
Epoch [40900/50000], Loss: 0.0019
Epoch [41000/50000], Loss: 0.0019
Epoch [41100/50000], Loss: 0.0018
Epoch [41200/50000], Loss: 0.0018
Epoch [41300/50000], Loss: 0.0017
Epoch [41400/50000], Loss: 0.0017
Epoch [41500/50000], Loss: 0.0017
Epoch [41600/50000], Loss: 0.0016
Epoch [41700/50000], Loss: 0.0016
Epoch [41800/50000], Loss: 0.0015
Epoch [41900/50000], Loss: 0.0015
Epoch [42000/50000], Loss: 0.0015
Epoch [42100/50000], Loss: 0.0014
Epoch [42200/50000], Loss: 0.0014
Epoch [42300/50000], Loss: 0.0014
Epoch [42400/50000], Loss: 0.0014
Epoch [42500/50000], Loss: 0.0013
Epoch [42600/50000], Loss: 0.0013
Epoch [42700/50000], Loss: 0.0013
Epoch [42800/50000], Loss: 0.0012
Epoch [42900/50000], Loss: 0.0012
Epoch [43000/50000], Loss: 0.0012
Epoch [43100/50000], Loss: 0.0012
Epoch [43200/50000], Loss: 0.0011
Epoch [43300/50000], Loss: 0.0011
Epoch [43400/50000], Loss: 0.0011
Epoch [43500/50000], Loss: 0.0011
Epoch [43600/50000], Loss: 0.0010
Epoch [43700/50000], Loss: 0.0010
Epoch [43800/50000], Loss: 0.0010
Epoch [43900/50000], Loss: 0.0010
Epoch [44000/50000], Loss: 0.0009
Epoch [44100/50000], Loss: 0.0009
Epoch [44200/50000], Loss: 0.0009
Epoch [44300/50000], Loss: 0.0009
Epoch [44400/50000], Loss: 0.0009
Epoch [44500/50000], Loss: 0.0008
Epoch [44600/50000], Loss: 0.0008
Epoch [44700/50000], Loss: 0.0008
Epoch [44800/50000], Loss: 0.0008
Epoch [44900/50000], Loss: 0.0008
Epoch [45000/50000], Loss: 0.0007
Epoch [45100/50000], Loss: 0.0007
Epoch [45200/50000], Loss: 0.0007
Epoch [45300/50000], Loss: 0.0007
Epoch [45400/50000], Loss: 0.0007
Epoch [45500/50000], Loss: 0.0007
Epoch [45600/50000], Loss: 0.0007
Epoch [45700/50000], Loss: 0.0006
Epoch [45800/50000], Loss: 0.0006
Epoch [45900/50000], Loss: 0.0006
Epoch [46000/50000], Loss: 0.0006
Epoch [46100/50000], Loss: 0.0006
Epoch [46200/50000], Loss: 0.0006
Epoch [46300/50000], Loss: 0.0006
Epoch [46400/50000], Loss: 0.0005
Epoch [46500/50000], Loss: 0.0005
Epoch [46600/50000], Loss: 0.0005
Epoch [46700/50000], Loss: 0.0005
Epoch [46800/50000], Loss: 0.0005
Epoch [46900/50000], Loss: 0.0005
Epoch [47000/50000], Loss: 0.0005
Epoch [47100/50000], Loss: 0.0005
Epoch [47200/50000], Loss: 0.0005
Epoch [47300/50000], Loss: 0.0004
Epoch [47400/50000], Loss: 0.0004
Epoch [47500/50000], Loss: 0.0004
Epoch [47600/50000], Loss: 0.0004
Epoch [47700/50000], Loss: 0.0004
Epoch [47800/50000], Loss: 0.0004
Epoch [47900/50000], Loss: 0.0004
Epoch [48000/50000], Loss: 0.0004
Epoch [48100/50000], Loss: 0.0004
Epoch [48200/50000], Loss: 0.0004
Epoch [48300/50000], Loss: 0.0004
Epoch [48400/50000], Loss: 0.0003
Epoch [48500/50000], Loss: 0.0003
Epoch [48600/50000], Loss: 0.0003
Epoch [48700/50000], Loss: 0.0003
Epoch [48800/50000], Loss: 0.0003
Epoch [48900/50000], Loss: 0.0003
Epoch [49000/50000], Loss: 0.0003
Epoch [49100/50000], Loss: 0.0003
Epoch [49200/50000], Loss: 0.0003
Epoch [49300/50000], Loss: 0.0003
Epoch [49400/50000], Loss: 0.0003
Epoch [49500/50000], Loss: 0.0003
Epoch [49600/50000], Loss: 0.0003
Epoch [49700/50000], Loss: 0.0003
Epoch [49800/50000], Loss: 0.0003
Epoch [49900/50000], Loss: 0.0002
Epoch [50000/50000], Loss: 0.0002

In [13]:
# Step 4: Print the learned weights and bias
print(f"\nLearned weights and bias:")
print(f"w1: {w1.item():.2f}, w2: {w2.item():.2f}, w3: {w3.item():.2f}, bias: {bias.item():.2f}")

Learned weights and bias:
w1: 12.00, w2: 5.99, w3: 2.01, bias: 19.94

In [17]:
df.head()

  employee_id  performance  years_of_experience  projects_completed  bonus
0     EMP_001            7                    2                   4    124
1     EMP_002            4                    1                   4     82
2     EMP_003            8                    7                  10    178
3     EMP_004            5                    7                   8    138
4     EMP_005            7                    8                   9    170

In [19]:
predicted_bonus = w1 * 7 + w2 * 2 + w3 * 4 + bias
predicted_bonus

tensor([123.9888], grad_fn=<AddBackward0>)

In [18]:
predicted_bonus = w1 * 4 + w2 * 1 + w3 * 4 + bias
predicted_bonus

tensor([81.9901], grad_fn=<AddBackward0>)